<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hrconnect</groupId>
        <artifactId>pom-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>pom-parent</relativePath>
    </parent>

    <groupId>com.hrconnect</groupId>
    <artifactId>hrconnectpro-root</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>HRConnectPro Root</name>
    <description>Plateforme RH event-driven pour la gestion des employés, congés, entretiens et paie</description>

    <modules>
        <!-- Modules de soclage (à builder en premier) -->
        <module>pom-parent</module>
        <module>socle</module>

        <!-- Modules métier -->
        <module>employee</module>
        <module>leave</module>
    </modules>

    <!-- Les properties et dependencyManagement sont maintenant dans pom-parent -->

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>

