<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hrconnect</groupId>
        <artifactId>pom-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom-parent</relativePath>
    </parent>

    <artifactId>socle</artifactId>
    <packaging>pom</packaging>

    <name>Socle Technique</name>
    <description>Module parent du socle technique partagé entre tous les microservices</description>

    <modules>
        <module>socle-common</module>
        <module>socle-persistence</module>
        <module>socle-kafka</module>
        <module>socle-security</module>
        <module>socle-test</module>
    </modules>
</project>
