<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hrconnect</groupId>
        <artifactId>pom-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom-parent</relativePath>
    </parent>

    <artifactId>payroll</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Payroll Module</name>
    <description>Module parent pour le service Payroll et son contrat</description>

    <modules>
        <module>payroll-contract</module>
        <module>payroll-service</module>
    </modules>
</project>
